.TH "BIF3" "1" "June  27, 2005" "Sergio Cayuqueo" "Debian GNU/Linux"

.SH "NAME"
\fBbif3\fP \- PHP Framework for Web Applications development

.SH "DESCRIPTION"
This manual page documents briefly the \fBbif3\fP webpage.
.PP
This manual page was written for the Debian distribution
because the original program does not have a man page.

.PP 
\fBBuild it Fast (BIF)\fP  is a PHP Framework. It contains
several classes that help you develop complex Web
applications in a short amount of time. It brings
the concept of the 'widget' to Web development.
It features Cascade Skins and transparent session
management.
The actual location of the bif3 files is \fI/usr/share/bif3\fP.

.SH "AUTHOR"
This manual page was written by Sergio Cayuqueo <linuxvarela@yahoo.com.ar>,
for the Debian system (but may be used by others).
